In [1]:
import pandas as pd

In [3]:
data = pd.read_csv(r"C:\Users\Ashraful\Downloads\pndas_project.csv")

In [5]:
data

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012,0.0,-2.1,86,30,11.3,99.89,Snow

In [7]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012,-1.5,-3.3,88,7,4.8,101.23,Fog

In [9]:
data.shape

(8784, 8)

In [11]:
data.index

RangeIndex(start=0, stop=8784, step=1)

In [13]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [15]:
data.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [17]:
data['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [21]:
data.nunique()

Date/Time           366
Temp_C              533
Dew Point Temp_C    489
Rel Hum_%            83
Wind Speed_km/h      34
Visibility_km        24
Press_kPa           518
Weather              50
dtype: int64

In [25]:
data.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

In [27]:
data['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

 # Q) 1. Find all the unique "Wind Speed" values in the data.

In [41]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012,-1.5,-3.3,88,7,4.8,101.23,Fog

In [43]:
data.nunique()

Date/Time           366
Temp_C              533
Dew Point Temp_C    489
Rel Hum_%            83
Wind Speed_km/h      34
Visibility_km        24
Press_kPa           518
Weather              50
dtype: int64

In [49]:
data['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2],
      dtype=int64)

# Q) 2. Find the number of times when the 'Weather exactly is Clear'

In [52]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012,-1.5,-3.3,88,7,4.8,101.23,Fog

In [56]:
data['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

In [58]:
data[data['Weather']== 'Clear']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012,-13.8,-16.5,80,24,25.0,101.52,Clear

In [62]:
data.groupby('Weather').get_group('Clear')

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012,-13.8,-16.5,80,24,25.0,101.52,Clear

# Q) 3.Find the number of times when the 'Wind Speed was exactly 4 km/h'

In [69]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012,-1.5,-3.3,88,7,4.8,101.23,Fog

In [71]:
data[data['Wind Speed_km/h'] == 4]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog
96,1/5/2012,-8.8,-11.7,79,4,9.7,100.32,Snow
101,1/5/2012,-7.0,-9.5,82,4,4.0,100.19,Snow
146,1/7/2012,-8.1,-11.1,79,4,19.3,100.15,Cloudy
...,...,...,...,...,...,...,...,...
8768,12/31/2012,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,12/31/2012,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,12/31/2012,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8772,12/31/2012,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,12/31/2012,-4.6,-6.6,86,4,12.9,100.63,Snow

# Q) 4. Find out the all null values in the data

In [74]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012,-1.5,-3.3,88,7,4.8,101.23,Fog

In [76]:
data.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [78]:
data.notnull().sum()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

# Q) 5. Rename the column name 'Weather of the data frame to Weather Condition'

In [81]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012,-1.5,-3.3,88,7,4.8,101.23,Fog

In [91]:
data.rename(columns = {'Weather': 'Weather Condition'}, inplace = True)

In [93]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012,-1.5,-3.3,88,7,4.8,101.23,Fog

# Q) 6. What is the mean 'visibility'?

In [97]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog

In [99]:
data['Visibility_km'].mean()

27.664446721311478

# Q) 7. What is the Standard Deviation of 'Pressure' in this data?

In [102]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog

In [104]:
data['Press_kPa'].std()

0.8440047459486474

# Q) 8. What is the variance of 'Relative Humidity' in this data?

In [107]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog

In [109]:
data['Rel Hum_%'].var()

286.2485501984998

# Q) 9. Find all instances when 'Snow' was recorded

In [116]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012,-1.5,-3.3,88,7,4.8,101.23,Fog

In [118]:
data['Weather Condition'].value_counts()

Weather Condition
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

In [122]:
data[data['Weather Condition'] == 'Snow']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
55,1/3/2012,-14.0,-19.5,63,19,25.0,100.95,Snow
84,1/4/2012,-13.7,-21.7,51,11,24.1,101.25,Snow
86,1/4/2012,-11.3,-19.0,53,7,19.3,100.97,Snow
87,1/4/2012,-10.2,-16.3,61,11,9.7,100.89,Snow
88,1/4/2012,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,12/31/2012,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012,0.0,-2.1,86,30,11.3,99.89,Snow

In [136]:
data[data['Weather Condition'].str.contains('Snow')].tail(50)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
8680,12/27/2012,-4.5,-6.2,88,37,2.0,100.44,"Snow,Blowing Snow"
8681,12/27/2012,-4.2,-5.9,88,32,3.2,100.47,"Snow,Blowing Snow"
8682,12/27/2012,-4.0,-5.7,88,28,8.0,100.49,"Snow,Blowing Snow"
8683,12/27/2012,-3.9,-5.6,88,26,9.7,100.52,"Snow,Blowing Snow"
8684,12/27/2012,-3.7,-5.3,89,37,16.1,100.58,Snow
8685,12/27/2012,-3.7,-4.8,92,24,4.8,100.62,"Freezing Drizzle,Snow"
8686,12/27/2012,-3.8,-4.6,94,20,4.8,100.65,"Freezing Drizzle,Snow"
8687,12/27/2012,-4.0,-5.6,89,24,9.7,100.70,Snow
8688,12/28/2012,-4.2,-5.7,89,19,8.0,100.78,"Freezing Drizzle,Snow"
8689,12/28/2012,-4.4,-6.6,85,15,6.4,100.83,"Freezing Drizzle,Snow"
8690,12/28/2012,-4.3,-6.3,86,11,12.9,100.93,"Freezing Drizzle,Snow"
8691,12/28/2012,-4.6,-5.9,91,13,4.0,101.01,Snow
8692,12/28/2012,-4.9,-5.9,93,9,9.7,101.00,Snow
8723,12/29/2012,-10.9,-12.2,90,7,6.4,101.09,"Snow Showers,Fog"
8724,12/29/2012,-10.5,-11.6,92,11,8.0,100.93,"Snow Showers,Fog"
8725,12/29/2012,-10.0,-11.1,92,22,9.7,100.63,"Snow Showers,Fog"
8726,12/29/2012,-9.3,-10.5,91,22,4.8,100.60,"Snow,Fog"
8727,12/29/2012,-8.8,-10.0,91,20,1.2,100.55,"Snow,Fog"
8728,12/29/2012,-8.5,-9.9,90,24,1.2,100.49,"Snow,Fog"
8729,12/29/2012,-9.0,-10.4,90,19,2.4,100.46,"Snow,Fog"
8730,12/29/2012,-9.3,-10.9,88,26,6.4,100.38,"Snow,Fog"
8731,12/29/2012,-9.5,-11.2,87,26,3.2,100.33,"Snow,Fog"
8732,12/29/2012,-9.7,-11.6,86,24,9.7,100.25,"Snow,Fog"
8733,12/29/2012,-9.8,-11.8,85,24,8.0,100.24,"Snow,Fog"
8734,12/29/2012,-10.1,-11.6,89,15,2.4,100.20,"Snow,Fog"
8735,12/29/2012,-10.0,-12.0,85,20,6.4,100.19,"Snow,Fog"
8736,12/30/2012,-9.6,-11.3,87,13,3.2,100.23,"Snow,Fog"
8737,12/30/2012,-9.4,-10.5,92,9,2.4,100.22,"Snow,Fog"
8738,12/30/2012,-9.3,-10.4,92,9,4.0,100.28,"Snow,Fog"
8739,12/30/2012,-9.1,-10.4,90,11,3.6,100.30,"Snow,Fog"
8740,12/30/2012,-9.3,-10.6,90,13,9.7,100.28,"Snow,Fog"
8741,12/30/2012,-9.1,-10.4,90,11,4.0,100.32,"Snow,Fog"
8742,12/30/2012,-9.3,-10.8,89,17,8.0,100.39,"Snow,Fog"
8767,12/31/2012,-9.3,-11.3,85,0,19.3,101.19,Snow Showers
8768,12/31/2012,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,12/31/2012,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,12/31/2012,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8771,12/31/2012,-6.7,-7.9,91,9,9.7,100.93,Snow
8772,12/31/2012,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,12/31/2012,-4.6,-6.6,86,4,12.9,100.63,Snow
8774,12/31/2012,-3.4,-5.7,84,6,11.3,100.57,Snow
8775,12/31/2012,-2.3,-4.6,84,9,9.7,100.47,Snow
8776,12/31/2012,-1.4,-4.0,82,13,12.9,100.40,Snow
8777,12/31/2012,-1.1,-3.3,85,19,9.7,100.30,Snow
8778,12/31/2012,-1.3,-3.1,88,17,9.7,100.19,Snow
8779,12/31/2012,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012,0.0,-2.1,86,30,11.3,99.89,Snow

# Q) 10. Find all instances when "Wind is speed above 24" and Visibility is 25'.

In [141]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog

In [149]:
 data[(data['Wind Speed_km/h'] < 24) & (data['Visibility_km'] == 25)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
20,1/1/2012,3.2,1.3,87,19,25.0,99.50,Cloudy
21,1/1/2012,4.0,1.7,85,20,25.0,99.39,Cloudy
41,1/2/2012,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
46,1/2/2012,-7.0,-14.7,54,20,25.0,100.26,Cloudy
49,1/3/2012,-9.7,-17.2,54,20,25.0,100.43,Cloudy
...,...,...,...,...,...,...,...,...
8762,12/31/2012,-10.1,-13.4,77,9,25.0,101.45,Cloudy
8763,12/31/2012,-11.8,-14.4,81,6,25.0,101.42,Mostly Cloudy
8764,12/31/2012,-10.5,-12.8,83,11,25.0,101.34,Cloudy
8765,12/31/2012,-10.2,-12.4,84,6,25.0,101.28,Cloudy
8766,12/31/2012,-9.7,-11.7,85,4,25.0,101.23,Cloudy

# Q) 11. What is the Mean value each of column against each 'Weather condition'

In [165]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog

# Q) 12. What is the Maximum and Minimum value of each column aginst each 'Weather Condition'?

In [182]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog

In [192]:
data.groupby('Weather Condition').min().head(5)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather Condition,,,,,,,
Clear,1/11/2012,-23.3,-28.5,20,0,11.3,99.52
Cloudy,1/1/2012,-21.4,-26.8,18,0,11.3,98.39
Drizzle,1/23/2012,1.1,-0.2,74,0,6.4,97.84
"Drizzle,Fog",1/23/2012,0.0,-1.6,85,0,1.0,98.65
"Drizzle,Ice Pellets,Fog",12/17/2012,0.4,-0.7,92,20,4.0,100.79

In [194]:
data.groupby('Weather Condition').max().head(5)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather Condition,,,,,,,
Clear,9/9/2012,32.8,20.4,99,33,48.3,103.63
Cloudy,9/9/2012,30.5,22.6,99,54,48.3,103.65
Drizzle,9/30/2012,18.8,17.7,96,30,25.0,101.56
"Drizzle,Fog",9/30/2012,19.9,19.1,100,28,9.7,102.07
"Drizzle,Ice Pellets,Fog",12/17/2012,0.4,-0.7,92,20,4.0,100.79

# Q) 13. Show all the Records where Weather Condition is Fog

In [197]:
data[data['Weather Condition']== 'Fog']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog
4,1/1/2012,-1.5,-3.3,88,7,4.8,101.23,Fog
5,1/1/2012,-1.4,-3.3,87,9,6.4,101.27,Fog
6,1/1/2012,-1.5,-3.1,89,7,6.4,101.29,Fog
...,...,...,...,...,...,...,...,...
8716,12/29/2012,-16.0,-17.2,90,6,9.7,101.25,Fog
8717,12/29/2012,-14.8,-15.9,91,4,6.4,101.25,Fog
8718,12/29/2012,-13.8,-15.3,88,4,9.7,101.25,Fog
8719,12/29/2012,-14.8,-16.4,88,7,8.0,101.22,Fog
8722,12/29/2012,-12.0,-13.3,90,7,6.4,101.15,Fog

# Q) 14. Find all instances when 'Weather is Clear or Visibility is above 40'.

In [206]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog

In [208]:
data['Weather Condition'].value_counts()

Weather Condition
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

In [212]:
data[(data['Weather Condition'] == 'Clear') | (data['Visibility_km'] > 40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
67,1/3/2012,-16.9,-24.8,50,24,25.0,101.74,Clear
106,1/5/2012,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,12/30/2012,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,12/30/2012,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,12/30/2012,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,12/30/2012,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,12/30/2012,-13.8,-16.5,80,24,25.0,101.52,Clear

# Q) 15. Find all instance When:
   ###  A. 'Weather is Clear' and 'Relative Humidity is greater than 50'
   ### or
   ### 'Visibility is above 40'

In [218]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012,-1.8,-3.7,87,4,8.0,101.24,Fog

In [220]:
data[(data['Weather Condition'] == 'Clear') & (data['Rel Hum_%'] > 50) | (data['Visibility_km'] > 40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
106,1/5/2012,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
110,1/5/2012,-5.1,-10.7,65,22,48.3,100.46,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,12/30/2012,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,12/30/2012,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,12/30/2012,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,12/30/2012,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,12/30/2012,-13.8,-16.5,80,24,25.0,101.52,Clear